language: node_js

node_js:
  - "0.10"

branches:
  only:
    - master

script:
  - export COVERALLS_SERVICE_NAME=travis-pro
  - export COVERALLS_REPO_TOKEN=wEPmOB8VfKBdChU8hQ9tv9LfkeQHRl16D
  - npm test
  - npm run coverage
